-- 1. Przygotuj bazę danych na podstawie schematu

CREATE TABLE REGIONS (
    region_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_name VARCHAR2(100) NOT NULL
);

CREATE TABLE countries (
    country_id CHAR(2) PRIMARY KEY,
    country_name VARCHAR2(40),
    region_id NUMBER,
    FOREIGN KEY (region_id) REFERENCES regions(region_id)
);

CREATE TABLE locations (
    location_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street_address VARCHAR2(100),
    postal_code VARCHAR2(20),
    city VARCHAR2(50),
    state_province VARCHAR2(50),
    country_id CHAR(2)
);

CREATE TABLE jobs (
    job_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_title VARCHAR2(50) NOT NULL,
    min_salary NUMBER,
    max_salary NUMBER
);

CREATE TABLE departments (
    department_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR2(50) NOT NULL,
    manager_id NUMBER,
    location_id NUMBER
);

CREATE TABLE employees (
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) UNIQUE,
    phone_numer VARCHAR2(20),
    hire_date DATE NOT NULL,
    job_id NUMBER,
    salary NUMBER(8,2),
    commission_pct NUMBER(2,2),
    manager_id NUMBER,
    department_id NUMBER
);

CREATE TABLE job_history (
    employee_id NUMBER,
    start_date DATE,
    job_id NUMBER,
    department_id NUMBER,
    PRIMARY KEY (employee_id, start_date)
);

-- 1.3. Część kolumn oraz kluczy obcych dodaj za pomocą polecenia ALTER TABLE

ALTER TABLE job_history
ADD (end_date DATE);

ALTER TABLE locations
ADD CONSTRAINT fk_locations_countries
FOREIGN KEY (country_id) REFERENCES countries(country_id);

ALTER TABLE departments
ADD CONSTRAINT fk_departments_locations
FOREIGN KEY (location_id) REFERENCES locations(location_id);

ALTER TABLE departments
ADD CONSTRAINT fk_departments_manager
FOREIGN KEY (manager_id) REFERENCES employees(employee_id);

ALTER TABLE employees
ADD CONSTRAINT fk_employees_manager
FOREIGN KEY (manager_id) REFERENCES employees(employee_id);

ALTER TABLE employees
ADD CONSTRAINT fk_employees_jobs
FOREIGN KEY (job_id) REFERENCES jobs(job_id);

ALTER TABLE employees
ADD CONSTRAINT fk_employees_departments
FOREIGN KEY (department_id) REFERENCES departments(department_id);

ALTER TABLE job_history
ADD CONSTRAINT fk_job_history_jobs
FOREIGN KEY (job_id) REFERENCES jobs(job_id);

ALTER TABLE job_history
ADD CONSTRAINT fk_job_history_departments
FOREIGN KEY (department_id) REFERENCES departments(department_id);

-- 1.4. W tabeli JOBS ustaw warunek (CHECK), taki aby min_salary było mniejsze
-- od max_salary co najmniej o 2000

ALTER TABLE jobs
ADD CONSTRAINT chk_jobs_salary
CHECK (max_salary - min_salary >= 2000);

-- 2. Wstaw 4 rekordy do tabeli JOBS

INSERT INTO jobs (job_title, min_salary, max_salary)
VALUES ('Programista', 5000, 30000);

INSERT INTO jobs (job_title, min_salary, max_salary)
VALUES ('Sprzedawca', 4000, 12000);

INSERT INTO jobs (job_title, min_salary, max_salary)
VALUES ('Pracownik HR', 4000, 10000);

INSERT INTO jobs (job_title, min_salary, max_salary)
VALUES ('Nauczyciel', 4000, 9000);

-- 3. Wstaw 4 rekordy do tabeli EMPLOYEES

INSERT INTO employees (first_name, last_name, email, hire_date, job_id, salary)
VALUES ('Jacek', 'Placek', 'JPlacek@wp.pl', DATE '2020-01-15', '6', '30000');

INSERT INTO employees (first_name, last_name, email, hire_date, job_id, salary)
VALUES ('Marta', 'Wiśniewska', 'MWisnia@wp.pl', DATE '2024-04-25', '7', '6000');

INSERT INTO employees (first_name, last_name, email, hire_date, job_id, salary)
VALUES ('Janusz', 'Kowalski', 'JKowalski@wp.pl', DATE '2010-12-01', '8', '10000');

INSERT INTO employees (first_name, last_name, email, hire_date, job_id, salary)
VALUES ('Ewelina', 'Nowak', 'ENowak@wp.pl', DATE '2025-01-05', '4', '7000');

-- 4. W tabeli EMPLOYEES zmień menadżera pracownikom o id 2 i 3 na 1

UPDATE employees
SET manager_id = 1
WHERE employee_id IN (2, 3);

-- 5. Dla tabeli JOBS zwiększ minimalne i maksymalne wynagrodzenie o 500
-- jeśli nazwa zawiera 'b' lub 's'

UPDATE jobs
SET min_salary = min_salary + 500,
    max_salary = max_salary + 500
WHERE LOWER(job_title) LIKE '%b%'
   OR LOWER(job_title) LIKE '%s%';
   
-- 6. Z tabeli JOBS usuń rekordy, dla których 
-- maksymalne zarobki są większe od 9000

DELETE FROM employees
WHERE job_id IN (
    SELECT job_id FROM jobs
    WHERE max_salary > 9000
);

DELETE FROM jobs
WHERE max_salary > 9000;

-- 7. Usuń jedną z tabel i sprawdzź czy możesz ją odzyskać

DROP TABLE regions CASCADE CONSTRAINTS;
